### ISSUE TITLE
Win10 64-Bit - 

### ISSUE THREAD

**Issue by gontunes** [SelmiAbderrahim/YouLikeHitsBot#1]
I tried running this on Windows but I had some issues. 

C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master>YouLikeHitsBot.py
Traceback (most recent call last):
  File "C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master\YouLikeHitsBot.py", line 2, in <module>
    pyarmor_runtime()
  File "C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master\pytransform\__init__.py", line 342, in pyarmor_runtime
    pyarmor_init(path, is_runtime=1, suffix=suffix)
  File "C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master\pytransform\__init__.py", line 337, in pyarmor_init
    _pytransform = _load_library(path, is_runtime, platid, suffix)
  File "C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master\pytransform\__init__.py", line 302, in _load_library
    raise PytransformError('Could not find "%s"' % filename)
pytransform.PytransformError: Could not find "C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master\pytransform\platforms\windows\x86\_pytransform.dll"

C:\Users\xxxx\Documents\YT Bots\YouLikeHitsBot-master\YouLikeHitsBot-master>pause

**Comment by SelmiAbderrahim** [comment]
It's not working Windows. But today I'll update it.

**Comment by SelmiAbderrahim** [comment]
Wait for the video about using this code on Windows
